version: '3'
services:
  web:
    build: .
    command: ./run_docker_mode.sh
    depends_on:
      - "athena"
      - "elasticsearch"
    ports:
      - "8080:8080"
  athena:
    build: ./athena
    command: ./run_docker_mode.sh
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - "mongo"
      - "beanstalk"
  beanstalk:
    image: kusmierz/beanstalkd
    ports:
      - "11300:11300"
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - "9200:9200"