version: '3'
services:
  # web:
  #   build: .
  #   command: npm start
  #   depends_on:
  #     - "athena"
  athena:
    build: ./athena
    command: ./run_docker_mode.sh
    depends_on:
      - "beanstalk"
      - "mongo"
  beanstalk:
    image: kusmierz/beanstalkd
    ports:
      - "11300:11300"
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
