version: '3'
services:
  web:
    build: .
    command: ./run_docker_mode.sh
    depends_on:
      - "athena"
    ports:
      - "8080:8080"
  athena:
    build: ./athena
    command: ["./wait-for-it.sh", "./run_docker_mode.sh"]
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - "mongo"
      - "beanstalk"
  beanstalk:
    image: kusmierz/beanstalkd
    ports:
      - "11300:11300"
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"