version: '3'
services:
  # web:
  #   build: .
  #   command: npm start
  #   depends_on:
  #     - "athena"
  athena:
    build: ./athena
    command: ./run_docker_mode.sh
    depends_on:
      - "beanstalk"
      - "mongo"
  beanstalk:
    image: schickling/beanstalkd
  mongo:
    image: mongo:3.2
    environment:
      MONGO_INITDB_DATABASE: MAPPRDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
